// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package pins

import "encoding/json"
import "errors"
import "fmt"
import "regexp"
import "time"
import "unicode/utf8"

type PinAnnotations struct {
	// EstateJorisjonkersDevPausedAt corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-at".
	EstateJorisjonkersDevPausedAt *time.Time `json:"estate.jorisjonkers.dev/paused-at,omitempty,omitzero"`

	// EstateJorisjonkersDevPausedBy corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-by".
	EstateJorisjonkersDevPausedBy *string `json:"estate.jorisjonkers.dev/paused-by,omitempty,omitzero"`

	// EstateJorisjonkersDevPausedReason corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-reason".
	EstateJorisjonkersDevPausedReason *string `json:"estate.jorisjonkers.dev/paused-reason,omitempty,omitzero"`

	// EstateJorisjonkersDevRollbackFragment corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/rollback-fragment".
	EstateJorisjonkersDevRollbackFragment *string `json:"estate.jorisjonkers.dev/rollback-fragment,omitempty,omitzero"`

	// EstateJorisjonkersDevRollbackVersion corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/rollback-version".
	EstateJorisjonkersDevRollbackVersion *string `json:"estate.jorisjonkers.dev/rollback-version,omitempty,omitzero"`
}

type PinAnnotations_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PinAnnotations_0) UnmarshalJSON(value []byte) error {
	type Plain PinAnnotations_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PinAnnotations_0(plain)
	return nil
}

type PinAnnotations_1 struct {
	// EstateJorisjonkersDevPausedAt corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-at".
	EstateJorisjonkersDevPausedAt time.Time `json:"estate.jorisjonkers.dev/paused-at"`

	// EstateJorisjonkersDevPausedBy corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-by".
	EstateJorisjonkersDevPausedBy string `json:"estate.jorisjonkers.dev/paused-by"`

	// EstateJorisjonkersDevPausedReason corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-reason".
	EstateJorisjonkersDevPausedReason string `json:"estate.jorisjonkers.dev/paused-reason"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PinAnnotations_1) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["estate.jorisjonkers.dev/paused-at"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/paused-at in PinAnnotations_1: required")
	}
	if _, ok := raw["estate.jorisjonkers.dev/paused-by"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/paused-by in PinAnnotations_1: required")
	}
	if _, ok := raw["estate.jorisjonkers.dev/paused-reason"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/paused-reason in PinAnnotations_1: required")
	}
	type Plain PinAnnotations_1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.EstateJorisjonkersDevPausedBy)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "estate.jorisjonkers.dev/paused-by", 1)
	}
	if utf8.RuneCountInString(string(plain.EstateJorisjonkersDevPausedReason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "estate.jorisjonkers.dev/paused-reason", 1)
	}
	*j = PinAnnotations_1(plain)
	return nil
}

type PinAnnotations_2 struct {
	// EstateJorisjonkersDevPausedAt corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-at".
	EstateJorisjonkersDevPausedAt time.Time `json:"estate.jorisjonkers.dev/paused-at"`

	// EstateJorisjonkersDevPausedBy corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-by".
	EstateJorisjonkersDevPausedBy string `json:"estate.jorisjonkers.dev/paused-by"`

	// EstateJorisjonkersDevPausedReason corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/paused-reason".
	EstateJorisjonkersDevPausedReason string `json:"estate.jorisjonkers.dev/paused-reason"`

	// EstateJorisjonkersDevRollbackFragment corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/rollback-fragment".
	EstateJorisjonkersDevRollbackFragment string `json:"estate.jorisjonkers.dev/rollback-fragment"`

	// EstateJorisjonkersDevRollbackVersion corresponds to the JSON schema field
	// "estate.jorisjonkers.dev/rollback-version".
	EstateJorisjonkersDevRollbackVersion string `json:"estate.jorisjonkers.dev/rollback-version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PinAnnotations_2) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["estate.jorisjonkers.dev/paused-at"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/paused-at in PinAnnotations_2: required")
	}
	if _, ok := raw["estate.jorisjonkers.dev/paused-by"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/paused-by in PinAnnotations_2: required")
	}
	if _, ok := raw["estate.jorisjonkers.dev/paused-reason"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/paused-reason in PinAnnotations_2: required")
	}
	if _, ok := raw["estate.jorisjonkers.dev/rollback-fragment"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/rollback-fragment in PinAnnotations_2: required")
	}
	if _, ok := raw["estate.jorisjonkers.dev/rollback-version"]; raw != nil && !ok {
		return fmt.Errorf("field estate.jorisjonkers.dev/rollback-version in PinAnnotations_2: required")
	}
	type Plain PinAnnotations_2
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.EstateJorisjonkersDevPausedBy)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "estate.jorisjonkers.dev/paused-by", 1)
	}
	if utf8.RuneCountInString(string(plain.EstateJorisjonkersDevPausedReason)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "estate.jorisjonkers.dev/paused-reason", 1)
	}
	if matched, _ := regexp.MatchString(`^(?:[^@\s/]+\/)+[^@\s/:]+@sha256:[a-f0-9]{64}$`, string(plain.EstateJorisjonkersDevRollbackFragment)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "EstateJorisjonkersDevRollbackFragment", `^(?:[^@\s/]+\/)+[^@\s/:]+@sha256:[a-f0-9]{64}$`)
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+$`, string(plain.EstateJorisjonkersDevRollbackVersion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "EstateJorisjonkersDevRollbackVersion", `^\d+\.\d+\.\d+$`)
	}
	*j = PinAnnotations_2(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PinAnnotations) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var pinAnnotations_0 PinAnnotations_0
	var pinAnnotations_1 PinAnnotations_1
	var pinAnnotations_2 PinAnnotations_2
	var errs []error
	if err := pinAnnotations_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := pinAnnotations_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := pinAnnotations_2.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain PinAnnotations
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PinAnnotations(plain)
	return nil
}
