// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package lock

import "encoding/json"
import "fmt"
import "regexp"
import "time"
import "unicode/utf8"

type ChainLink struct {
	// Commit corresponds to the JSON schema field "commit".
	Commit string `json:"commit"`

	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp time.Time `json:"timestamp"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChainLink) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["commit"]; raw != nil && !ok {
		return fmt.Errorf("field commit in ChainLink: required")
	}
	if _, ok := raw["digest"]; raw != nil && !ok {
		return fmt.Errorf("field digest in ChainLink: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in ChainLink: required")
	}
	type Plain ChainLink
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-f0-9]{40}$`, string(plain.Commit)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Commit", `^[a-f0-9]{40}$`)
	}
	if matched, _ := regexp.MatchString(`^sha256:[a-f0-9]{64}$`, string(plain.Digest)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Digest", `^sha256:[a-f0-9]{64}$`)
	}
	*j = ChainLink(plain)
	return nil
}

type CompositionLock struct {
	// ApiVersion corresponds to the JSON schema field "apiVersion".
	ApiVersion string `json:"apiVersion"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata CompositionLockMetadata `json:"metadata"`

	// Spec corresponds to the JSON schema field "spec".
	Spec CompositionLockSpec `json:"spec"`
}

type CompositionLockMetadata struct {
	// Cluster corresponds to the JSON schema field "cluster".
	Cluster string `json:"cluster"`

	// GeneratedAt corresponds to the JSON schema field "generatedAt".
	GeneratedAt time.Time `json:"generatedAt"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompositionLockMetadata) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cluster"]; raw != nil && !ok {
		return fmt.Errorf("field cluster in CompositionLockMetadata: required")
	}
	if _, ok := raw["generatedAt"]; raw != nil && !ok {
		return fmt.Errorf("field generatedAt in CompositionLockMetadata: required")
	}
	type Plain CompositionLockMetadata
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Cluster)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "cluster", 1)
	}
	*j = CompositionLockMetadata(plain)
	return nil
}

type CompositionLockSpec struct {
	// ClusterStateDigest corresponds to the JSON schema field "clusterStateDigest".
	ClusterStateDigest string `json:"clusterStateDigest"`

	// ComposedDigest corresponds to the JSON schema field "composedDigest".
	ComposedDigest string `json:"composedDigest"`

	// Fragments corresponds to the JSON schema field "fragments".
	Fragments CompositionLockSpecFragments `json:"fragments"`

	// Isolated corresponds to the JSON schema field "isolated".
	Isolated CompositionLockSpecIsolated `json:"isolated,omitempty,omitzero"`

	// LockChain corresponds to the JSON schema field "lockChain".
	LockChain []ChainLink `json:"lockChain"`

	// PreviousLockDigest corresponds to the JSON schema field "previousLockDigest".
	PreviousLockDigest *string `json:"previousLockDigest,omitempty,omitzero"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion"`

	// ToolkitVersion corresponds to the JSON schema field "toolkitVersion".
	ToolkitVersion string `json:"toolkitVersion"`
}

type CompositionLockSpecFragments map[string]LockedFragment

type CompositionLockSpecIsolated map[string]Isolation

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompositionLockSpec) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["clusterStateDigest"]; raw != nil && !ok {
		return fmt.Errorf("field clusterStateDigest in CompositionLockSpec: required")
	}
	if _, ok := raw["composedDigest"]; raw != nil && !ok {
		return fmt.Errorf("field composedDigest in CompositionLockSpec: required")
	}
	if _, ok := raw["fragments"]; raw != nil && !ok {
		return fmt.Errorf("field fragments in CompositionLockSpec: required")
	}
	if _, ok := raw["lockChain"]; raw != nil && !ok {
		return fmt.Errorf("field lockChain in CompositionLockSpec: required")
	}
	if _, ok := raw["schemaVersion"]; raw != nil && !ok {
		return fmt.Errorf("field schemaVersion in CompositionLockSpec: required")
	}
	if _, ok := raw["toolkitVersion"]; raw != nil && !ok {
		return fmt.Errorf("field toolkitVersion in CompositionLockSpec: required")
	}
	type Plain CompositionLockSpec
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^sha256:[a-f0-9]{64}$`, string(plain.ClusterStateDigest)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ClusterStateDigest", `^sha256:[a-f0-9]{64}$`)
	}
	if matched, _ := regexp.MatchString(`^sha256:[a-f0-9]{64}$`, string(plain.ComposedDigest)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ComposedDigest", `^sha256:[a-f0-9]{64}$`)
	}
	if plain.PreviousLockDigest != nil {
		if matched, _ := regexp.MatchString(`^sha256:[a-f0-9]{64}$`, string(*plain.PreviousLockDigest)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "PreviousLockDigest", `^sha256:[a-f0-9]{64}$`)
		}
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+$`, string(plain.SchemaVersion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "SchemaVersion", `^\d+\.\d+\.\d+$`)
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+$`, string(plain.ToolkitVersion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ToolkitVersion", `^\d+\.\d+\.\d+$`)
	}
	*j = CompositionLockSpec(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompositionLock) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["apiVersion"]; raw != nil && !ok {
		return fmt.Errorf("field apiVersion in CompositionLock: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in CompositionLock: required")
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in CompositionLock: required")
	}
	if _, ok := raw["spec"]; raw != nil && !ok {
		return fmt.Errorf("field spec in CompositionLock: required")
	}
	type Plain CompositionLock
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ApiVersion != "resolved.jorisjonkers.dev/v1" {
		return fmt.Errorf("field %s: must be equal to %s", "apiVersion", "resolved.jorisjonkers.dev/v1")
	}
	if plain.Kind != "CompositionLock" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "CompositionLock")
	}
	*j = CompositionLock(plain)
	return nil
}

type Isolation struct {
	// Codes corresponds to the JSON schema field "codes".
	Codes []string `json:"codes"`

	// Refused corresponds to the JSON schema field "refused".
	Refused string `json:"refused"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Isolation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["codes"]; raw != nil && !ok {
		return fmt.Errorf("field codes in Isolation: required")
	}
	if _, ok := raw["refused"]; raw != nil && !ok {
		return fmt.Errorf("field refused in Isolation: required")
	}
	type Plain Isolation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Codes != nil && len(plain.Codes) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "codes", 1)
	}
	if matched, _ := regexp.MatchString(`^(?:[^@\s/]+\/)+[^@\s/:]+@sha256:[a-f0-9]{64}$`, string(plain.Refused)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Refused", `^(?:[^@\s/]+\/)+[^@\s/:]+@sha256:[a-f0-9]{64}$`)
	}
	*j = Isolation(plain)
	return nil
}

type LockedFragment struct {
	// InputsSha corresponds to the JSON schema field "inputsSha".
	InputsSha string `json:"inputsSha"`

	// Project corresponds to the JSON schema field "project".
	Project string `json:"project"`

	// Ref corresponds to the JSON schema field "ref".
	Ref string `json:"ref"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository"`

	// Revisions corresponds to the JSON schema field "revisions".
	Revisions LockedFragmentRevisions `json:"revisions"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion"`

	// SourceSha corresponds to the JSON schema field "sourceSha".
	SourceSha string `json:"sourceSha"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version"`
}

type LockedFragmentRevisions map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *LockedFragment) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["inputsSha"]; raw != nil && !ok {
		return fmt.Errorf("field inputsSha in LockedFragment: required")
	}
	if _, ok := raw["project"]; raw != nil && !ok {
		return fmt.Errorf("field project in LockedFragment: required")
	}
	if _, ok := raw["ref"]; raw != nil && !ok {
		return fmt.Errorf("field ref in LockedFragment: required")
	}
	if _, ok := raw["repository"]; raw != nil && !ok {
		return fmt.Errorf("field repository in LockedFragment: required")
	}
	if _, ok := raw["revisions"]; raw != nil && !ok {
		return fmt.Errorf("field revisions in LockedFragment: required")
	}
	if _, ok := raw["schemaVersion"]; raw != nil && !ok {
		return fmt.Errorf("field schemaVersion in LockedFragment: required")
	}
	if _, ok := raw["sourceSha"]; raw != nil && !ok {
		return fmt.Errorf("field sourceSha in LockedFragment: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in LockedFragment: required")
	}
	type Plain LockedFragment
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-f0-9]{64}$`, string(plain.InputsSha)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "InputsSha", `^[a-f0-9]{64}$`)
	}
	if utf8.RuneCountInString(string(plain.Project)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "project", 1)
	}
	if matched, _ := regexp.MatchString(`^(?:[^@\s/]+\/)+[^@\s/:]+@sha256:[a-f0-9]{64}$`, string(plain.Ref)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Ref", `^(?:[^@\s/]+\/)+[^@\s/:]+@sha256:[a-f0-9]{64}$`)
	}
	if matched, _ := regexp.MatchString(`^[^/\s]+\/[^/\s]+$`, string(plain.Repository)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Repository", `^[^/\s]+\/[^/\s]+$`)
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+$`, string(plain.SchemaVersion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "SchemaVersion", `^\d+\.\d+\.\d+$`)
	}
	if matched, _ := regexp.MatchString(`^[a-f0-9]{40}$`, string(plain.SourceSha)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "SourceSha", `^[a-f0-9]{40}$`)
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+$`, string(plain.Version)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Version", `^\d+\.\d+\.\d+$`)
	}
	*j = LockedFragment(plain)
	return nil
}
