// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package clusterstate

import "encoding/json"
import "fmt"
import "regexp"
import "time"
import "unicode/utf8"

type Snapshot struct {
	// ApiVersion corresponds to the JSON schema field "apiVersion".
	ApiVersion string `json:"apiVersion"`

	// Bindings corresponds to the JSON schema field "bindings".
	Bindings []SnapshotBindingsElem `json:"bindings"`

	// CapturedAt corresponds to the JSON schema field "capturedAt".
	CapturedAt time.Time `json:"capturedAt"`

	// Cluster corresponds to the JSON schema field "cluster".
	Cluster string `json:"cluster"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind"`

	// Placements corresponds to the JSON schema field "placements".
	Placements []SnapshotPlacementsElem `json:"placements"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion"`
}

type SnapshotBindingsElem struct {
	// Claim corresponds to the JSON schema field "claim".
	Claim string `json:"claim"`

	// Node corresponds to the JSON schema field "node".
	Node string `json:"node"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SnapshotBindingsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["claim"]; raw != nil && !ok {
		return fmt.Errorf("field claim in SnapshotBindingsElem: required")
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in SnapshotBindingsElem: required")
	}
	type Plain SnapshotBindingsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Claim)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "claim", 1)
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	*j = SnapshotBindingsElem(plain)
	return nil
}

type SnapshotPlacementsElem struct {
	// Node corresponds to the JSON schema field "node".
	Node string `json:"node"`

	// Process corresponds to the JSON schema field "process".
	Process string `json:"process"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SnapshotPlacementsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["node"]; raw != nil && !ok {
		return fmt.Errorf("field node in SnapshotPlacementsElem: required")
	}
	if _, ok := raw["process"]; raw != nil && !ok {
		return fmt.Errorf("field process in SnapshotPlacementsElem: required")
	}
	type Plain SnapshotPlacementsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Node)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "node", 1)
	}
	if utf8.RuneCountInString(string(plain.Process)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "process", 1)
	}
	*j = SnapshotPlacementsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Snapshot) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["apiVersion"]; raw != nil && !ok {
		return fmt.Errorf("field apiVersion in Snapshot: required")
	}
	if _, ok := raw["bindings"]; raw != nil && !ok {
		return fmt.Errorf("field bindings in Snapshot: required")
	}
	if _, ok := raw["capturedAt"]; raw != nil && !ok {
		return fmt.Errorf("field capturedAt in Snapshot: required")
	}
	if _, ok := raw["cluster"]; raw != nil && !ok {
		return fmt.Errorf("field cluster in Snapshot: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Snapshot: required")
	}
	if _, ok := raw["placements"]; raw != nil && !ok {
		return fmt.Errorf("field placements in Snapshot: required")
	}
	if _, ok := raw["schemaVersion"]; raw != nil && !ok {
		return fmt.Errorf("field schemaVersion in Snapshot: required")
	}
	type Plain Snapshot
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ApiVersion != "state.jorisjonkers.dev/v1" {
		return fmt.Errorf("field %s: must be equal to %s", "apiVersion", "state.jorisjonkers.dev/v1")
	}
	if utf8.RuneCountInString(string(plain.Cluster)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "cluster", 1)
	}
	if plain.Kind != "ClusterState" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "ClusterState")
	}
	if matched, _ := regexp.MatchString(`^\d+\.\d+\.\d+$`, string(plain.SchemaVersion)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "SchemaVersion", `^\d+\.\d+\.\d+$`)
	}
	*j = Snapshot(plain)
	return nil
}
